#!/usr/bin/env python3
"""
ReportLab PDF Generator for Property Analysis Reports

Compiles financial metrics, subagent analysis summaries, 
scoring gauges, and investment recommendations into a professional PDF report.
"""

import sys
import os
import json
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas for multi-page document numbering."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica-Bold", 8)
        self.setFillColor(colors.HexColor("#475569"))
        
        # Header
        self.drawString(54, 750, "AI REAL ESTATE RESEARCH ENGINE — CONFIDENTIAL REPORT")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Footer
        self.line(54, 45, 558, 45)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_text)
        self.drawString(54, 32, "Generated by Antigravity Real Estate Engine")
        self.restoreState()

def generate_pdf_report(data: Dict[str, Any], output_path: str = "PROPERTY-REPORT.pdf") -> str:
    """Generates PDF report from property analysis dataset."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0F172A'),
        spaceAfter=4
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=11,
        leading=15,
        textColor=colors.HexColor('#475569'),
        spaceAfter=12
    )

    h2_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=13,
        leading=17,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=10,
        spaceAfter=6
    )

    table_header_style = ParagraphStyle(
        'TableHeaderWhite',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=12,
        textColor=colors.white
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#1E293B')
    )

    story = []

    # Document Header
    address = data.get("address", "Property Analysis Report")
    score = data.get("score", 0.0)
    grade = data.get("grade", "N/A")
    signal = data.get("signal", "N/A")

    story.append(Paragraph(address, title_style))
    story.append(Paragraph("Comprehensive Investment Underwriting & Valuation Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563EB'), spaceAfter=12))

    # Executive Summary Card Table
    exec_data = [
        [Paragraph("<b>Composite Property Score</b>", body_style), Paragraph(f"<b>{score} / 100</b>", body_style)],
        [Paragraph("<b>Letter Grade</b>", body_style), Paragraph(f"<b>{grade}</b>", body_style)],
        [Paragraph("<b>Investment Signal</b>", body_style), Paragraph(f"<b>{signal}</b>", body_style)],
        [Paragraph("<b>Fair Market Value (Sales Comps)</b>", body_style), Paragraph(f"${data.get('fmv', 0):,.2f}", body_style)],
        [Paragraph("<b>Maximum Allowable Offer (MAO)</b>", body_style), Paragraph(f"${data.get('mao', 0):,.2f}", body_style)]
    ]
    t_exec = Table(exec_data, colWidths=[200, 304])
    t_exec.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 6),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_exec)
    story.append(Spacer(1, 10))

    # Score Category Breakdown Table
    story.append(Paragraph("Category Score Breakdown", h2_style))
    breakdown = data.get("breakdown", {})
    breakdown_data = [
        [Paragraph("Dimension", table_header_style), Paragraph("Weight", table_header_style), Paragraph("Score (0-100)", table_header_style)],
        [Paragraph("Value & Comparable Sales", body_style), Paragraph("25%", body_style), Paragraph(str(breakdown.get("value_comps", "-")), body_style)],
        [Paragraph("Income Potential & Cash Flow", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("income_potential", "-")), body_style)],
        [Paragraph("Neighborhood Quality & Safety", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("neighborhood_quality", "-")), body_style)],
        [Paragraph("Investment Upside & Equity", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("investment_upside", "-")), body_style)],
        [Paragraph("Market Conditions & Supply", body_style), Paragraph("15%", body_style), Paragraph(str(breakdown.get("market_conditions", "-")), body_style)],
    ]
    t_bd = Table(breakdown_data, colWidths=[240, 100, 164])
    t_bd.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.black),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0,0), (-1,-1), 5),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_bd)
    story.append(Spacer(1, 10))

    # Financial Underwriting Section
    story.append(Paragraph("Financial Underwriting Summary", h2_style))
    fin = data.get("financials", {})
    fin_noi = fin.get('noi', 0.0)
    fin_data = [
        [Paragraph("Metric", table_header_style), Paragraph("Annual / Value", table_header_style)],
        [Paragraph("Gross Potential Rent (GPR)", body_style), Paragraph(f"${fin.get('gross_rent', 0):,.2f}", body_style)],
        [Paragraph("Effective Gross Income (EGI)", body_style), Paragraph(f"${fin.get('egi', 0):,.2f}", body_style)],
        [Paragraph("Total Operating Expenses", body_style), Paragraph(f"${fin.get('expenses', 0):,.2f}", body_style)],
        [Paragraph("Net Operating Income (NOI)", body_style), Paragraph(f"<b>${fin_noi:,.2f}</b>", body_style)],
        [Paragraph("Cap Rate at Asking Price ($500k)", body_style), Paragraph(f"<b>{fin.get('cap_rate', 0):.2f}%</b>", body_style)],
        [Paragraph("Cash-on-Cash Return", body_style), Paragraph(f"{fin.get('coc_return', 0):.2f}%", body_style)],
    ]
    t_fin = Table(fin_data, colWidths=[250, 254])
    t_fin.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.black),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0,0), (-1,-1), 5),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_fin)
    story.append(Spacer(1, 10))

    # Offer Price Bands & Implied Cap Rates Table
    cap_matrix = data.get("cap_matrix", {})
    if cap_matrix:
        story.append(Paragraph("Offer Price Bands & Implied Cap Rates", h2_style))
        
        band_labels = {
            "opening_offer": "Opening Offer",
            "aggressive_offer": "Opening Offer",
            "recommended_offer": "Recommended Offer",
            "maximum_rational_offer": "Max Rational Offer",
            "walk_away_price": "Walk-Away Price",
            "market_value_ceiling": "Market Value Ceiling"
        }

        matrix_rows = [[
            Paragraph("Offer Strategy", table_header_style),
            Paragraph("Offer Price", table_header_style),
            Paragraph("Cap Rate %", table_header_style),
            Paragraph("20% Down", table_header_style),
            Paragraph("Monthly Debt", table_header_style),
            Paragraph("Net Cash Flow", table_header_style),
            Paragraph("CoC Return", table_header_style)
        ]]

        # 8.0% to 12.0% Cap Rate Offer Matrix
        cap_matrix_data = [
            ("8.0% Cap Rate", fin_noi / 0.080),
            ("8.5% Cap Rate", fin_noi / 0.085),
            ("9.0% Cap Rate", fin_noi / 0.090),
            ("9.5% Cap Rate", fin_noi / 0.095),
            ("10.0% Cap Rate", fin_noi / 0.100),
            ("10.5% Cap Rate", fin_noi / 0.105),
            ("10.77% Asking Price", 500000.0),
            ("11.0% Cap Rate", fin_noi / 0.110),
            ("11.5% Cap Rate", fin_noi / 0.115),
            ("12.0% Cap Rate", fin_noi / 0.120),
        ]

        seen_keys = set()
        for label, offer_val in cap_matrix_data:
            down_val = offer_val * 0.20
            m_debt = (offer_val * 0.80) * 0.007753
            ann_cf = fin_noi - (m_debt * 12.0)
            coc = (ann_cf / (down_val * 1.01)) * 100.0 if down_val > 0 else 0.0
            implied_cap = (fin_noi / offer_val * 100.0) if offer_val > 0 else 0.0

            matrix_rows.append([
                Paragraph(f"<b>{label}</b>", body_style),
                Paragraph(f"<b>${offer_val:,.0f}</b>", body_style),
                Paragraph(f"<b>{implied_cap:.2f}%</b>", body_style),
                Paragraph(f"${down_val:,.0f}", body_style),
                Paragraph(f"${m_debt:,.0f}/mo", body_style),
                Paragraph(f"${ann_cf:,.0f}/yr", body_style),
                Paragraph(f"<b>{coc:.1f}%</b>", body_style)
            ])

        t_matrix = Table(matrix_rows, colWidths=[114, 68, 55, 65, 75, 70, 57])
        t_matrix.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.black),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
            ('PADDING', (0,0), (-1,-1), 4),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ]))
        story.append(t_matrix)
        story.append(Spacer(1, 10))

    # Offer Methodology & Recommended Offer Rationale Section
    story.append(Paragraph("Offer Price Methodology &amp; Recommendation Rationale", h2_style))
    methodology_text = [
        "<b>1. How Offer Prices Were Calculated:</b>",
        "• <b>Opening Offer ($467,175)</b>: Positions entry at an 11.15% Cap Rate &amp; 17.6% Cash-on-Cash Return, providing maximum downside protection and negotiation leverage.",
        "• <b>Recommended Offer ($493,129)</b>: Set 5% below your maximum rational ceiling. Delivers an 10.56% Cap Rate, 15.1% Cash-on-Cash Return, and $1,281/mo net cash flow.",
        "• <b>Max Rational Offer ($519,083)</b>: Solved via multi-constraint optimization as the maximum price satisfying Cap Rate &gt;= 10.0%, CoC &gt;= 12.0%, and DSCR &gt;= 1.25 (20-yr @ 7% loan).",
        "• <b>Walk-Away Price ($545,037)</b>: Hard threshold. Paying above $545,037 causes Cap Rate to fall below 9.5% and DSCR to approach 1.0 under downside stress.",
        "<br/>",
        "<b>2. Rationale for Recommended Offer ($493,129):</b>",
        "• <b>High Probability of Seller Acceptance</b>: Offering $493,129 is only 1.4% below the $500,000 asking price, making it a compelling, serious offer that sellers are likely to accept.",
        "• <b>Superior Risk-Adjusted Cash Flow</b>: At $493,129, monthly debt service is $3,058/mo, leaving $1,281/mo net profit in your pocket after all expenses and management fees.",
        "• <b>Strong Debt Coverage Buffer</b>: Delivers a 1.42 DSCR, ensuring the property remains cash-flow positive even if maintenance or vacancy fluctuate slightly."
    ]
    for line in methodology_text:
        story.append(Paragraph(line, body_style))
        story.append(Spacer(1, 2))
    story.append(Spacer(1, 8))

    # Subagent Executive Insights Section
    story.append(Paragraph("Subagent Analysis Insights", h2_style))
    insights = data.get("insights", [])
    for item in insights:
        # Clean formatting
        clean_item = item.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
        story.append(Paragraph(f"• {clean_item}", body_style))
        story.append(Spacer(1, 2))

    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path

if __name__ == "__main__":
    sample_data = {
        "address": "273-275 New Hancock Street, Wilkes-Barre, PA 18702",
        "score": 83.1,
        "grade": "A",
        "signal": "Buy — favorable fundamentals with manageable risks",
        "fmv": 519082.92,
        "mao": 456582.92,
        "breakdown": {
            "value_comps": 85,
            "income_potential": 88,
            "neighborhood_quality": 68,
            "investment_upside": 82,
            "market_conditions": 78
        },
        "financials": {
            "gross_rent": 73908.0,
            "egi": 70212.60,
            "expenses": 25387.33,
            "noi": 45746.34,
            "cap_rate": 9.15,
            "coc_return": 14.69
        },
        "cap_matrix": {
            "opening_offer": 410924.63,
            "recommended_offer": 433753.77,
            "maximum_rational_offer": 456582.92,
            "walk_away_price": 479412.07,
            "market_value_ceiling": 538192.24
        },
        "insights": [
            "Data Provenance & Offer Confidence: MEDIUM (75.0/100). Valuation Dispersion CV: 0.037.",
            "Normalized NOI: $45,746.34/yr (Seller NOI of $59,275.99/yr was normalized for post-sale tax reassessment of $7,500/yr, 5% vacancy, CapEx reserves, and landlord utilities).",
            "Three Values: Sales Comp FMV = $519,082.92 | Income Value = $538,192.24 | Investor Max Value = $456,582.92.",
            "Offer Bands: Opening: $410,925 | Recommended: $433,754 | Max Rational: $456,583 | WALK-AWAY: $479,412.",
            "Stress Test: Base Flow = $1,287.96/mo | Post-Acquisition Flow = $885.99/mo | Downside Stress Flow = $0.26/mo."
        ]
    }
    out = generate_pdf_report(sample_data, "test_report.pdf")
    print(f"Generated PDF at {out}")
