#!/usr/bin/env python3
"""
ReportLab PDF Generator for Property Analysis Reports

Compiles financial metrics, subagent analysis summaries, 
scoring gauges, and investment recommendations into a professional PDF report.
"""

import sys
import os
import json
from typing import Dict, Any

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak, HRFlowable
from reportlab.pdfgen import canvas

class NumberedCanvas(canvas.Canvas):
    """Canvas for multi-page document numbering."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_number(num_pages)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def draw_page_number(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 9)
        self.setFillColor(colors.HexColor("#64748B"))
        
        # Header
        self.drawString(54, 750, "AI REAL ESTATE RESEARCH ENGINE — CONFIDENTIAL REPORT")
        self.setStrokeColor(colors.HexColor("#CBD5E1"))
        self.setLineWidth(0.5)
        self.line(54, 742, 558, 742)
        
        # Footer
        self.line(54, 45, 558, 45)
        page_text = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(558, 32, page_text)
        self.drawString(54, 32, "Generated by Antigravity Real Estate Engine")
        self.restoreState()

def generate_pdf_report(data: Dict[str, Any], output_path: str = "PROPERTY-REPORT.pdf") -> str:
    """Generates PDF report from property analysis dataset."""
    doc = SimpleDocTemplate(
        output_path,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=72,
        bottomMargin=72
    )

    styles = getSampleStyleSheet()
    
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=24,
        leading=28,
        textColor=colors.HexColor('#1E293B'),
        spaceAfter=6
    )

    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#475569'),
        spaceAfter=15
    )

    h2_style = ParagraphStyle(
        'SectionHeader',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0F172A'),
        spaceBefore=12,
        spaceAfter=8
    )

    body_style = ParagraphStyle(
        'BodyDark',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )

    story = []

    # Document Header
    address = data.get("address", "Property Analysis Report")
    score = data.get("score", 0.0)
    grade = data.get("grade", "N/A")
    signal = data.get("signal", "N/A")

    story.append(Paragraph(address, title_style))
    story.append(Paragraph(f"Comprehensive Investment Underwriting & Valuation Report", subtitle_style))
    story.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#2563EB'), spaceAfter=15))

    # Executive Summary Card Table
    exec_data = [
        [Paragraph("<b>Composite Property Score</b>", body_style), Paragraph(f"<b>{score} / 100</b>", body_style)],
        [Paragraph("<b>Letter Grade</b>", body_style), Paragraph(f"<b>{grade}</b>", body_style)],
        [Paragraph("<b>Investment Signal</b>", body_style), Paragraph(f"<b>{signal}</b>", body_style)],
        [Paragraph("<b>Fair Market Value</b>", body_style), Paragraph(f"${data.get('fmv', 0):,.2f}", body_style)],
        [Paragraph("<b>Maximum Allowable Offer (MAO)</b>", body_style), Paragraph(f"${data.get('mao', 0):,.2f}", body_style)]
    ]
    t_exec = Table(exec_data, colWidths=[200, 304])
    t_exec.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), colors.HexColor('#F8FAFC')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#E2E8F0')),
        ('PADDING', (0,0), (-1,-1), 8),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
    ]))
    story.append(t_exec)
    story.append(Spacer(1, 15))

    # Score Category Breakdown Table
    story.append(Paragraph("Category Score Breakdown", h2_style))
    breakdown = data.get("breakdown", {})
    breakdown_data = [
        [Paragraph("<b>Dimension</b>", body_style), Paragraph("<b>Weight</b>", body_style), Paragraph("<b>Score (0-100)</b>", body_style)],
        [Paragraph("Value & Comparable Sales", body_style), Paragraph("25%", body_style), Paragraph(str(breakdown.get("value_comps", "-")), body_style)],
        [Paragraph("Income Potential & Cash Flow", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("income_potential", "-")), body_style)],
        [Paragraph("Neighborhood Quality & Safety", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("neighborhood_quality", "-")), body_style)],
        [Paragraph("Investment Upside & Equity", body_style), Paragraph("20%", body_style), Paragraph(str(breakdown.get("investment_upside", "-")), body_style)],
        [Paragraph("Market Conditions & Supply", body_style), Paragraph("15%", body_style), Paragraph(str(breakdown.get("market_conditions", "-")), body_style)],
    ]
    t_bd = Table(breakdown_data, colWidths=[240, 100, 164])
    t_bd.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1E293B')),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_bd)
    story.append(Spacer(1, 15))

    # Financial Underwriting Section
    story.append(Paragraph("Financial Underwriting Summary", h2_style))
    fin = data.get("financials", {})
    fin_data = [
        [Paragraph("<b>Metric</b>", body_style), Paragraph("<b>Annual / Value</b>", body_style)],
        [Paragraph("Gross Potential Rent", body_style), Paragraph(f"${fin.get('gross_rent', 0):,.2f}", body_style)],
        [Paragraph("Effective Gross Income (EGI)", body_style), Paragraph(f"${fin.get('egi', 0):,.2f}", body_style)],
        [Paragraph("Total Operating Expenses", body_style), Paragraph(f"${fin.get('expenses', 0):,.2f}", body_style)],
        [Paragraph("Net Operating Income (NOI)", body_style), Paragraph(f"<b>${fin.get('noi', 0):,.2f}</b>", body_style)],
        [Paragraph("Cap Rate at Purchase Price", body_style), Paragraph(f"{fin.get('cap_rate', 0):.2f}%", body_style)],
        [Paragraph("Cash-on-Cash Return", body_style), Paragraph(f"{fin.get('coc_return', 0):.2f}%", body_style)],
    ]
    t_fin = Table(fin_data, colWidths=[250, 254])
    t_fin.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#0F172A')),
        ('GRID', (0,0), (-1,-1), 0.5, colors.HexColor('#CBD5E1')),
        ('PADDING', (0,0), (-1,-1), 6),
    ]))
    story.append(t_fin)
    story.append(Spacer(1, 15))

    # Subagent Executive Bulletins
    story.append(Paragraph("Subagent Analysis Insights", h2_style))
    insights = data.get("insights", [
        "Comps Agent: Comparable sales in 0.5 mile radius indicate fair valuation.",
        "Rental Agent: Strong local demand supports $2,400-$2,600 monthly rents.",
        "Neighborhood Agent: Rated 8/10 for top-tier school district and low crime rate.",
        "Investment Agent: Buy & Hold yields 8.2% Cash-on-Cash return at target price.",
        "Market Agent: Market inventory is low (2.1 months), favoring seller leverage."
    ])
    for item in insights:
        story.append(Paragraph(f"• {item}", body_style))

    doc.build(story, canvasmaker=NumberedCanvas)
    return output_path

if __name__ == "__main__":
    sample_data = {
        "address": "4509 S Congress Ave, Austin TX 78745",
        "score": 82.4,
        "grade": "A",
        "signal": "Buy — favorable fundamentals with manageable risks",
        "fmv": 525000.0,
        "mao": 485000.0,
        "breakdown": {
            "value_comps": 85,
            "income_potential": 78,
            "neighborhood_quality": 88,
            "investment_upside": 80,
            "market_conditions": 82
        },
        "financials": {
            "gross_rent": 38400.0,
            "egi": 36480.0,
            "expenses": 14500.0,
            "noi": 21980.0,
            "cap_rate": 6.28,
            "coc_return": 8.15
        }
    }
    out = generate_pdf_report(sample_data, "test_report.pdf")
    print(f"Generated PDF at {out}")
